# Generated by Django 3.0.3 on 2020-03-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
