# Generated by Django 3.0.4 on 2020-03-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0006_auto_20200321_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
