# Generated by Django 3.0.4 on 2020-03-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0008_auto_20200325_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
