# Generated by Django 2.2.12 on 2020-04-04 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0012_auto_20200404_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='ProductPurchaseEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvManage.PurchaseOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvManage.Product')),
            ],
        ),
    ]
