# Generated by Django 2.2.12 on 2020-04-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0013_auto_20200404_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpurchaseentry',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='ppentries',
            field=models.ManyToManyField(to='InvManage.ProductPurchaseEntry'),
        ),
    ]
