# Generated by Django 2.2.12 on 2020-04-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0015_auto_20200405_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='ordertotal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='subtotal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='taxtotal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='paid',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tax',
            field=models.FloatField(null=True),
        ),
    ]
