# Generated by Django 2.2.12 on 2020-04-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0016_auto_20200408_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchaseentry',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productpurchaseentry',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productpurchaseentry',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
