# Generated by Django 2.2.12 on 2020-04-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0017_auto_20200408_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
