# Generated by Django 2.2.12 on 2020-04-13 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0020_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='InvManage.Company')),
                ('po', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='InvManage.PurchaseOrder')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='shippingaddress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvManage.ShippingAddress'),
        ),
    ]
