# Generated by Django 2.2.12 on 2020-04-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0021_auto_20200413_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='identifier',
        ),
    ]
