# Generated by Django 2.2.12 on 2020-04-13 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0022_remove_shippingaddress_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='shippingaddress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvManage.ShippingAddress'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvManage.Company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='po',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvManage.PurchaseOrder'),
        ),
    ]
