# Generated by Django 2.2.12 on 2020-05-01 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0025_auto_20200420_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseFilterState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='productfiltercolumn',
            name='visible',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseFilterColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
                ('visible', models.BooleanField(default=True, null=True)),
                ('position', models.IntegerField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvManage.ProductFilterState')),
            ],
        ),
    ]
