# Generated by Django 2.2.12 on 2020-05-02 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0026_auto_20200501_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasefiltercolumn',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvManage.PurchaseFilterState'),
        ),
    ]
