# Generated by Django 2.2.12 on 2020-05-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0027_auto_20200502_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseFilterColumn',
        ),
    ]
