# Generated by Django 2.2.12 on 2020-05-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0028_delete_purchasefiltercolumn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductFilterColumn',
            new_name='FilterColumn',
        ),
    ]
