# Generated by Django 2.2.12 on 2020-05-02 09:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0031_auto_20200502_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductFilterState',
            new_name='FilterState',
        ),
        migrations.DeleteModel(
            name='PurchaseFilterState',
        ),
    ]
