# Generated by Django 2.2.12 on 2020-07-11 14:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0031_consumer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('so', models.IntegerField()),
                ('discount', models.FloatField(default=0, null=True)),
                ('tax', models.FloatField(default=0, null=True)),
                ('paid', models.FloatField(default=0, null=True)),
                ('balance', models.FloatField(default=0, null=True)),
                ('subtotal', models.FloatField(default=0, null=True)),
                ('taxtotal', models.FloatField(default=0, null=True)),
                ('ordertotal', models.FloatField(default=0, null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvManage.Consumer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSalesEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('discount', models.FloatField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvManage.PurchaseOrder')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvManage.Product')),
            ],
        ),
    ]
