# Generated by Django 2.2.12 on 2020-07-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0035_eventcard_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcard',
            name='objmodel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcard',
            name='objname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
