# Generated by Django 2.2.12 on 2020-07-22 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0036_auto_20200722_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='description',
        ),
    ]
