# Generated by Django 2.2.12 on 2020-07-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0037_remove_object_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcard',
            name='objId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
