# Generated by Django 2.2.12 on 2020-07-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0039_eventtype_historyfilterstate_objectmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventTypes', to='InvManage.HistoryFilterState'),
        ),
        migrations.AlterField(
            model_name='objectmodel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objModels', to='InvManage.HistoryFilterState'),
        ),
    ]
