# Generated by Django 2.2.12 on 2020-07-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0040_auto_20200725_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvManage.HistoryFilterState'),
        ),
        migrations.AlterField(
            model_name='objectmodel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvManage.HistoryFilterState'),
        ),
    ]
