# Generated by Django 2.2.12 on 2020-07-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0042_auto_20200726_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcard',
            name='operation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
