# Generated by Django 2.2.12 on 2020-07-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0043_auto_20200726_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcard',
            name='objname',
        ),
        migrations.AddField(
            model_name='eventcard',
            name='objname',
            field=models.ManyToManyField(to='InvManage.ObjectModel'),
        ),
        migrations.RemoveField(
            model_name='eventcard',
            name='operation',
        ),
        migrations.AddField(
            model_name='eventcard',
            name='operation',
            field=models.ManyToManyField(to='InvManage.EventType'),
        ),
    ]
