# Generated by Django 2.2.12 on 2020-07-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0045_auto_20200726_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcard',
            name='objmodel',
        ),
        migrations.AddField(
            model_name='eventcard',
            name='objmodel',
            field=models.ManyToManyField(to='InvManage.ObjectModel'),
        ),
        migrations.RemoveField(
            model_name='eventcard',
            name='objname',
        ),
        migrations.AddField(
            model_name='eventcard',
            name='objname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
