# Generated by Django 2.2.12 on 2020-07-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0047_auto_20200726_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='modName',
            field=models.CharField(default='old', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectmodel',
            name='modName',
            field=models.CharField(default='old', max_length=30),
            preserve_default=False,
        ),
    ]
