# Generated by Django 2.2.12 on 2020-07-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0048_auto_20200727_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='modName',
        ),
    ]
