# Generated by Django 2.2.12 on 2020-07-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0049_remove_eventtype_modname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcard',
            name='objmodel',
            field=models.ManyToManyField(related_name='objmodels', to='InvManage.ObjectModel'),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='operation',
            field=models.ManyToManyField(related_name='operations', to='InvManage.EventType'),
        ),
    ]
