# Generated by Django 2.2.12 on 2020-07-28 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0050_auto_20200728_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcard',
            name='objmodel',
        ),
        migrations.AddField(
            model_name='eventcard',
            name='objmodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InvManage.ObjectModel'),
        ),
        migrations.RemoveField(
            model_name='eventcard',
            name='operation',
        ),
        migrations.AddField(
            model_name='eventcard',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InvManage.EventType'),
        ),
    ]
