# Generated by Django 2.2.12 on 2020-07-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0051_auto_20200728_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcard',
            name='objmodel',
        ),
        migrations.AddField(
            model_name='eventcard',
            name='objmodel',
            field=models.ManyToManyField(to='InvManage.ObjectModel'),
        ),
        migrations.RemoveField(
            model_name='eventcard',
            name='operation',
        ),
        migrations.AddField(
            model_name='eventcard',
            name='operation',
            field=models.ManyToManyField(to='InvManage.EventType'),
        ),
    ]
