# Generated by Django 2.2.12 on 2020-07-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0052_auto_20200728_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcard',
            name='objmodel',
        ),
        migrations.AddField(
            model_name='eventcard',
            name='objmodel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='eventcard',
            name='operation',
        ),
        migrations.AddField(
            model_name='eventcard',
            name='operation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
