# Generated by Django 2.2.12 on 2020-07-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0053_auto_20200729_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcard',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
