# Generated by Django 2.2.12 on 2020-07-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0055_auto_20200730_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyfilterstate',
            name='events',
        ),
        migrations.RemoveField(
            model_name='historyfilterstate',
            name='mods',
        ),
        migrations.RemoveField(
            model_name='historyfilterstate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historyfilterstate',
            name='numEntries',
        ),
        migrations.AddField(
            model_name='historyfilterstate',
            name='params',
            field=models.TextField(null=True),
        ),
    ]
