# Generated by Django 2.2.12 on 2020-08-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0056_auto_20200731_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(max_length=20, null=True)),
                ('region', models.CharField(max_length=20, null=True)),
                ('route', models.CharField(max_length=20, null=True)),
                ('number', models.IntegerField(null=True)),
                ('acctype', models.CharField(blank=True, max_length=20, null=True)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('branchcode', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='English', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('minorder', models.IntegerField(blank=True, null=True)),
                ('contactperson', models.CharField(blank=True, max_length=50, null=True)),
                ('refcode', models.CharField(blank=True, max_length=20, null=True)),
                ('transportmode', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='location',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='post',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
