# Generated by Django 2.2.12 on 2020-10-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0060_auto_20201002_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateTimeField(blank=True, default='07 October, 2020', null=True),
        ),
    ]
