# Generated by Django 2.2.12 on 2020-10-11 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0061_auto_20201007_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnentry',
            name='ppes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InvManage.ProductPurchaseEntry'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateTimeField(blank=True, default='11 October, 2020', null=True),
        ),
    ]
