# Generated by Django 2.2.12 on 2020-10-22 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0062_auto_20201011_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnentry',
            name='ppes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InvManage.ProductPurchaseEntry'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateTimeField(blank=True, default='22 October, 2020', null=True),
        ),
    ]
