# Generated by Django 2.2.12 on 2021-02-07 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0065_auto_20210207_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='grninvoice',
            name='communication',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvManage.Communication'),
        ),
        migrations.AddField(
            model_name='grninvoice',
            name='shippingaddress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvManage.ShippingAddress'),
        ),
    ]
