# Generated by Django 2.2.12 on 2021-02-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0066_auto_20210207_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateTimeField(blank=True, default='09 February, 2021', null=True),
        ),
    ]
