# Generated by Django 2.2.12 on 2021-02-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0069_company_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='gstin',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gstin',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
