# Generated by Django 2.2.12 on 2021-02-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0070_auto_20210220_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateTimeField(blank=True, default='21 February, 2021', null=True),
        ),
    ]
