# Generated by Django 2.2.12 on 2021-09-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManage', '0072_auto_20210223_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateTimeField(blank=True, default='25 September, 2021', null=True),
        ),
    ]
